### ISSUE TITLE
Does stylegan3 support style mixing as in stylegan2?

### ISSUE THREAD

**Issue by jiazhi412** [NVlabs/stylegan3#123]
Does stylegan3 support style mixing as in stylegan2?

**Comment by PDillis** [comment]
Yes but not by design as mixing regularization has been turned off. We can still perform style mixing as before, but they won't be necessarily separated into `coarse`, `middle`, and `fine` styles. Indeed, now there are only `coarse` (layers 0 to 6) and `fine` (layers 7 to 14) for all models, irrespective of the resolution, but the results aren't really perfect (remember that in StyleGAN/2/2-ADA, there were 18 layers at `1024` resolution, 16 layers at `512` resolution, etc.). Check Appendix A and Figure 11 of the paper for more details.

![image](https://user-images.githubusercontent.com/24496178/155190307-9e9ecf1a-f858-4eea-964a-5322dc7c6bc9.png)

**Comment by jiazhi412** [comment]
Thank you so much for your explanation. Does StyleGAN2 yield better style mixing results? I mean, to study the style mixing, do you recommend to run experiments on StyleGAN2? 

Also, could you give me a little insights about why style mixing works better in 2 than 3 since the StyleGAN2 paper represent it as one of the main strengths but just turned it off in StyleGAN3?

**Comment by PDillis** [comment]
Yes, I think so from what I've done as manipulating the individual layers has yielded better style mixing in SGAN2. IMO, the reason to use StyleGAN3 is due to either the translation/rotation equivariance and/or the fact that there's no longer a need to align your dataset. If these are not important to you, then stick with StyleGAN2 (use the [ADA PyTorch](https://github.com/NVlabs/stylegan2-ada-pytorch) version though, as it trains faster).

As to why style mixing is turned off in StyleGAN3, the reason is that it wasn't going to be called StyleGAN3, but Alias-Free GAN. On Figure 5 of the [paper](https://nvlabs-fi-cdn.nvidia.com/stylegan3/stylegan3-paper.pdf), they note that turning on the mixing regularization wasn't detrimental to the model, but it is detrimental in more complex/multimodal datasets. As with Figure 11 that I posted above, they noted that styles could still be mixed, so it's ok to turn it off (but again, *not as well as* in StyleGAN2).

**Comment by jiazhi412** [comment]
I see. Thank you so much.
