### ISSUE TITLE
Make modified ops available in a separate library

### ISSUE THREAD

**Issue by Froskekongen** [NVlabs/stylegan3#24]
This is not a bug report.

Can you make the modified ops available as a standalone library? This would accelerate the use and experimentation using these ops outside the StyleGAN universe.

**Comment by jannehellsten** [comment]
The ops are in fact already separated into the `torch_utils` subfolder which you can use as a Python library if you point `PYTHONPATH` to the root of the stylegan3 checkout.  Then do `import torch_utils` and use the ops the same way StyleGAN3 code uses them.

We do not currently have plans to split them out of the stylegan3 repository into a separate repo or pip installable library.  We have considered this a few times so that we could host prebuilt wheel files for the CUDA ops, but in the end decided against this as this has fairly high maintenance cost (and we'd like to focus our work on pure research.)
