### ISSUE TITLE
Evaluating Metrics for very long 

### ISSUE THREAD

**Issue by Anonymud** [NVlabs/stylegan3#73]
Hello. I have the issue that when I want to generate new 512x512 images with my dataset I made with the native dataset tool it just prints the first tick and then evaluates metrics till I stop the script. What does evaluating Metrics mean and how can I fix this or make it faster?
Thanks

**Comment by PeterL1n** [comment]
I am just commenting out the eval code and get going...

**Comment by PDillis** [comment]
Metrics are used to evaluate the generated images in comparison to the dataset you feed it. For FID, the lower, the better. However, if you're not writing papers, they're not worth calculating. Set them off via `--metrics=none` when you run the code, otherwise, they take quite a bit to calculate.

**Comment by Anonymud** [comment]
OK thank you
Is it normal that it trains 1024*1024 images with an Tesla p100 gpu on colab for bout 2 hours per tick?

**Comment by PDillis** [comment]
Depends, StyleGAN3 config-r is far slower to train than config-t, and even more so than StyleGAN2/ADA. If you really want your model to have rotational and translational invariance, then go ahead with config-r. If only translational invariance suffices, go for config-t. Otherwise, if neither of these matters (as you have preprocessed your dataset, e.g., aligned the images), then stick with StyleGAN2 and save yourself time and headaches.

**Comment by Anonymud** [comment]
Thank you
